# Generated by Django 5.0.6 on 2024-07-10 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blogs/')),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Horses & Ponies', 'Horses & Ponies'), ('All Rounders', 'All Rounders'), ('Broodmares', 'Broodmares'), ('Dressage', 'Dressage'), ('Driving', 'Driving'), ('Eventers', 'Eventers'), ('Ex Race Horses', 'Ex Race Horses')], max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.CharField(choices=[('Foal', 'Foal'), ('Yearling', 'Yearling'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=20)),
                ('height', models.FloatField()),
                ('colour', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('auction_startdate', models.DateTimeField()),
                ('auction_enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.horse')),
            ],
            options={
                'ordering': ['-bid_time'],
            },
        ),
    ]
