# Generated by Django 5.0.6 on 2024-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
