# Generated by Django 5.0.6 on 2024-07-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_horse_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='contact',
            field=models.CharField(default=7976224241, max_length=50),
            preserve_default=False,
        ),
    ]
