# Generated by Django 5.0.6 on 2024-07-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_horse_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid_amount']},
        ),
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
