# Generated by Django 5.0.6 on 2024-07-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_bid_options_alter_horse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
