# Generated by Django 5.0.6 on 2024-07-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_horse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.CharField(choices=[('Thoroughbred', 'Thoroughbred'), ('Arabian', 'Arabian'), ('Quarter Horse', 'Quarter Horse'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='horse',
            name='colour',
            field=models.CharField(choices=[('Bay', 'Bay'), ('Chestnut', 'Chestnut'), ('Grey', 'Grey'), ('Black', 'Black')], max_length=20),
        ),
        migrations.AlterField(
            model_name='horse',
            name='location',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Europe', 'Europe'), ('Other', 'Other')], max_length=50),
        ),
    ]
