# Generated by Django 5.0.6 on 2024-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_horse_breed_alter_horse_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
