# Generated by Django 5.0.7 on 2024-07-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_horse_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
